name: development workflow

on: pull_request

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2

      - name: Use node 12.x
        uses: actions/setup-node@v1
        with:
          node-version: '12.x'
          registry-url: 'https://npm.pkg.github.com'
          scope: '@antecha'

      - name: install
        run: npm install --ignore-scripts
        env:
          NODE_AUTH_TOKEN: ${{ secrets.NPM_TOKEN }}

      - name: test_lint
        run: npm run lint

      - name: test_flow-type
        run: npm run flow

      - name: test_jest
        run: npm run test:ci

      - uses: codecov/codecov-action@v1
