name: preview workflow

on:
  pull_request:
  issue_comment:
    types: [created]

jobs:
  deploy_preview:
    runs-on: ubuntu-latest
    steps:
      - uses: khan/pull-request-comment-trigger@master
        id: check
        with:
          trigger: '#deploy'
          reaction: rocket
        env:
          GITHUB_TOKEN: '${{ secrets.GITHUB_TOKEN }}'

      - uses: actions/checkout@v1
        if: steps.check.outputs.triggered == 'true'

      - uses: actions/setup-node@v1
        with:
          node-version: '12.x'
          registry-url: https://registry.npmjs.org
        if: steps.check.outputs.triggered == 'true'

      - run: npm install
        if: steps.check.outputs.triggered == 'true'

      - run: npm run build
        if: steps.check.outputs.triggered == 'true'

      - uses: jakejarvis/s3-sync-action@master
        if: steps.check.outputs.triggered == 'true'
        with:
          args: --acl public-read --follow-symlinks --delete
        env:
          AWS_S3_BUCKET: ${{ secrets.AWS_S3_BUCKET_TESTING }}
          AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
          AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          AWS_REGION: 'eu-central-1'
          SOURCE_DIR: 'build'
