name: preview workflow

on:
  push:
    branches:
      - preview
  pull_request:
    types:
      - labeled

jobs:
  deploy_preview:
    if: contains(github.event.pull_request.labels.*.name, 'deploy preview') || github.ref == 'refs/heads/preview'
    runs-on: ubuntu-latests
    steps:
      - uses: actions/checkout@v1

      - uses: actions/setup-node@v1
        with:
          node-version: '12.x'
          registry-url: https://registry.npmjs.org

      - run: npm install

      - run: npm run build

      - uses: jakejarvis/s3-sync-action@master
        with:
          args: --acl public-read --follow-symlinks --delete
        env:
          AWS_S3_BUCKET: ${{ secrets.AWS_S3_BUCKET_TESTING }}
          AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
          AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          AWS_REGION: 'eu-central-1'
          SOURCE_DIR: 'build'
